# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

networks:
  api:
    external:
      name: api.reaction.localhost
  auth:
    external:
      name: auth.reaction.localhost
  reaction:
    external:
      name: reaction.localhost
  streams:
    external:
      name: streams.reaction.localhost

services:
  identity:
    image: reactioncommerce/identity:trunk
    env_file:
      - ./.env
    networks:
      api:
      auth:
      reaction:
      streams:
    ports:
      - "4100:4100"
